# Generated by Django 2.2.8 on 2020-08-08 15:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
