# Generated by Django 2.2.8 on 2020-08-11 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_auto_20200808_2110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='active',
        ),
        migrations.RemoveField(
            model_name='address',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='address',
            name='updated',
        ),
    ]
