# Generated by Django 2.2.8 on 2020-05-09 09:39

import builtins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200506_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.CharField(default=builtins.print, max_length=120),
            preserve_default=False,
        ),
    ]
