# Generated by Django 2.2.8 on 2020-05-09 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20200509_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Category',
            field=models.CharField(blank=True, default=None, max_length=120),
        ),
    ]
