# Generated by Django 2.2.8 on 2020-05-09 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20200509_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Category',
        ),
    ]
