# Generated by Django 2.2.8 on 2020-05-09 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_auto_20200509_1543'),
        ('products', '0014_auto_20200509_1606'),
    ]

    operations = [
    ]
