# Generated by Django 2.2.8 on 2020-08-12 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0026_product_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detail',
            field=models.TextField(default='Null', max_length=200),
        ),
    ]
