# Generated by Django 2.2.8 on 2020-08-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0027_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='detail',
            field=models.TextField(default='Null'),
        ),
    ]
