# Generated by Django 2.2.8 on 2020-08-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
