# Generated by Django 2.2.8 on 2020-05-21 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
