# Generated by Django 2.2.8 on 2020-07-03 10:20

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200703_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=phone_field.models.PhoneField(blank=True, default='8610125217', help_text='Contact phone number', max_length=31),
        ),
    ]
