# Generated by Django 2.2.8 on 2020-08-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_cartitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='isordered',
            field=models.BooleanField(default=False),
        ),
    ]
