# Generated by Django 2.2.8 on 2020-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_cart_isordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='isordered',
            field=models.IntegerField(default=1),
        ),
    ]
